### ISSUE TITLE
Create a dedicated client instead of MJPEG via HTTP

### ISSUE THREAD

**Issue by Maschell** [Maschell/StreamingPluginWiiU#4]
MJPEG via HTTP is simple to implement but sends each frame via TCP. 
A client that uses a UDP connection **may** be recuded lag and performance (untested), but would require more effort (and e.g. integrity checks).

When the encoder changed a decidated client has to be done anyway.

**Comment by Maschell** [comment]
Done

**Comment by piratesephiroth** [comment]
recuded and decidated, at last
