### ISSUE TITLE
Games do not start for me when this plugin is active

### ISSUE THREAD

**Issue by keef-khan** [Maschell/StreamingPluginWiiU#8]
I've tested with 3 games and tested when running other plugins and finally came to this conclusion. Games fail to boot when this plugin is active on my console. It loops with the game-booting music endlessly, for what I assume is any game. This is the only plugin I found that causes this to happen, but it means I can't actually play any games or actually get the console to stream anything to my computer.

**Comment by FiyaNinja** [comment]
I had the same issue. It seems to be a problem with the config files that the plugin makes. If you go into the plugins folder and delete the screenstreaming.cfg file, then it should work fine. (You'll have to reset the preferred resolution.)

**Comment by keef-khan** [comment]
Thanks this made it work, it even works on the home menu now.
